version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # avoid overwriting installed node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npx prisma generate && npm run dev"
