version: '3.9'

services:
  web:
    build:
      context: . # location of Dockerfile
      dockerfile: Dockerfile.dev # name of Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app # mounts local project into container
      - /app/node_modules  # avoid overwriting installed node_modules
    environment:
      - NODE_ENV=development 
      - CHOKIDAR_USEPOLLING=true  # Enable reliable file watching inside Docker
    command: sh -c "npx prisma generate && npm run dev"
